project:
  type: website

website:
  favicon: /images/flank-method-logo.png
  title: "The Flank Method"
  sidebar:
    style: "docked"
    title: "The Flank Method"
    logo: /images/Goethe-Logo.jpg
    search: true
    contents:
      - section: 'Welcome'
        contents:
          - index.qmd
      - section: 'Basics'
        contents:
          - flank-method.qmd
          - measurement.qmd
          - glossary.qmd
      - section: 'Data Reduction'
        contents:
          - data-reduction-program.qmd
          - datasets.qmd
          - video-tutorials.qmd
          - docs.qmd
      - section: 'Publications'
        contents:
          - method-section.qmd
          - literature.qmd
          - how-to-cite.qmd
      - section: 'Code Documentation'
        contents:
          - step-by-step.qmd
          - github.qmd
      - section: 'Dev'
        contents:
          - epma/epma-file-convert.qmd
  page-footer: 'Copyright 2023, The Flank Method Team'

margin-header: |
  ![](/images/flank-method-logo.png){width=50%}

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



