project:
  type: website

website:
  title: "Flank Method World"
  navbar:
    left:
      # - href: index.qmd
      #   text: Home
      - tutorials.qmd
      - About.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



